testmodConvParGF – GF_standalone
testmodConvParGF Program
CC-GPL3
321 statements
Source File
Uses
modConvParGF
modGate
Calls
Contents
Variables
mzp mxp myp ngrid ngrids_cp iens mynum npatch i0 j0 ia ja iz jz mgmxp mgmyp mgmzp ims ime jms jme kms kme its ite jts jte kts maxiens n_aer fscav rgas cp rm p00 tcrit g cpor xl akmin tkmin zmn ztn flip up vp wp rv rtp theta thp pp pi0 dn0 tend_pt rcp tkep zt3d zm3d dm3d rv2 buoy_exc qexp hexcp ls_ice ls_liq ls_clfrac patch_area aot500 temp2m rtgt sflux_r sflux_t topt rshort xland sfc_press lons lats col_sat cnv_frc tke_pbl wlpool dtlt time conprr xmb_deep apr_gr apr_w apr_mc apr_st apr_as xmb_shallow err_deep mass_flux_dp mass_flux_sh mass_flux_md weight_gr weight_w weight_mc weight_st weight_as aa0 aa1 aa2 aa3 aa1_bl aa1_cin tau_bl tau_ec xmbdn lightn_dens var2d zkbcon stochastic_sig rh_dicy_fct aa1_adv aa1_radpbl sc_aer sc_chem src_aer src_chem thsrc rtsrc clsrc nisrc nlsrc usrc vsrc mup lsfth advf_t lsfrt lsfth_sh lsfrt_sh src_buoy revsu_gf pfil_gf var3d_agf var3d_bgf var3d_cgf var3d_dgf itime1 sub_qils sub_qlls sub_cfls ierr4d jmin4d kdet4d k224d kbcon4d ktop4d kpbl4d klcl4d kstabi4d kstabm4d do_this_column cprr4d xmb4d edt4d sigma4d pwav4d pcup5d up_massentr5d up_massdetr5d dd_massentr5d dd_massdetr5d zup5d zdn5d prup5d prdn5d clwup5d tup5d conv_cld_fr5d grid_length kpbl land jk nruns version klon_local klev_local kte nrec nvx nvar nvartotal klevgrads int_byte_size n1 n2 n3 real_byte_size init_stat
Variables
Type Attributes Name Initial
integer, parameter :: mzp = 200
integer, parameter :: mxp = 1
integer, parameter :: myp = 1
integer, parameter :: ngrid = 1
integer, parameter :: ngrids_cp = 1
integer, parameter :: iens = 1
integer, parameter :: mynum = 1
integer, parameter :: npatch = 1
integer, parameter :: i0 = 1
integer, parameter :: j0 = 1
integer, parameter :: ia = 1
integer, parameter :: ja = 1
integer, parameter :: iz = 1
integer, parameter :: jz = 1
integer, parameter :: mgmxp = mxp
integer, parameter :: mgmyp = myp
integer, parameter :: mgmzp = mzp
integer, parameter :: ims = 1
integer, parameter :: ime = mxp
integer, parameter :: jms = 1
integer, parameter :: jme = myp
integer, parameter :: kms = 1
integer, parameter :: kme = mzp
integer, parameter :: its = ia
integer, parameter :: ite = iz
integer, parameter :: jts = ja
integer, parameter :: jte = jz
integer, parameter :: kts = 1
integer, parameter :: maxiens = 3
integer, parameter :: n_aer = 1
real :: fscav(n_aer)
real, parameter :: rgas = 287.
real, parameter :: cp = 1004.
real, parameter :: rm = 461.
real, parameter :: p00 = 1.e5
real, parameter :: tcrit = 273.15
real, parameter :: g = 9.80
real, parameter :: cpor = cp/rgas
real, parameter :: xl = 2.5e6
real, parameter :: akmin = 1.0
real, parameter :: tkmin = 1.e-5
real, dimension(kms:kme) :: zmn
real, dimension(kms:kme) :: ztn
integer, dimension(kms:kme) :: flip
real, dimension(kms:kme , ims:ime , jms:jme) :: up
real, dimension(kms:kme , ims:ime , jms:jme) :: vp
real, dimension(kms:kme , ims:ime , jms:jme) :: wp
real, dimension(kms:kme , ims:ime , jms:jme) :: rv
real, dimension(kms:kme , ims:ime , jms:jme) :: rtp
real, dimension(kms:kme , ims:ime , jms:jme) :: theta
real, dimension(kms:kme , ims:ime , jms:jme) :: thp
real, dimension(kms:kme , ims:ime , jms:jme) :: pp
real, dimension(kms:kme , ims:ime , jms:jme) :: pi0
real, dimension(kms:kme , ims:ime , jms:jme) :: dn0
real, dimension(kms:kme , ims:ime , jms:jme) :: tend_pt
real, dimension(kms:kme , ims:ime , jms:jme) :: rcp
real, dimension(kms:kme , ims:ime , jms:jme) :: tkep
real, dimension(kms:kme , ims:ime , jms:jme) :: zt3d
real, dimension(kms:kme , ims:ime , jms:jme) :: zm3d
real, dimension(kms:kme , ims:ime , jms:jme) :: dm3d
real, dimension(kms:kme , ims:ime , jms:jme) :: rv2
real, dimension(kms:kme , ims:ime , jms:jme) :: buoy_exc
real, dimension(kms:kme , ims:ime , jms:jme) :: qexp
real, dimension(kms:kme , ims:ime , jms:jme) :: hexcp
real, dimension(p_nmp,kms:kme , ims:ime , jms:jme) :: ls_ice
real, dimension(p_nmp,kms:kme , ims:ime , jms:jme) :: ls_liq
real, dimension(p_nmp,kms:kme , ims:ime , jms:jme) :: ls_clfrac
real, dimension(ims:ime , jms:jme,npatch) :: patch_area
real, dimension(ims:ime , jms:jme) :: aot500
real, dimension(ims:ime , jms:jme) :: temp2m
real, dimension(ims:ime , jms:jme) :: rtgt
real, dimension(ims:ime , jms:jme) :: sflux_r
real, dimension(ims:ime , jms:jme) :: sflux_t
real, dimension(ims:ime , jms:jme) :: topt
real, dimension(ims:ime , jms:jme) :: rshort
real, dimension(ims:ime , jms:jme) :: xland
real, dimension(ims:ime , jms:jme) :: sfc_press
real, dimension(ims:ime , jms:jme) :: lons
real, dimension(ims:ime , jms:jme) :: lats
real, dimension(ims:ime , jms:jme) :: col_sat
real, dimension(ims:ime , jms:jme) :: cnv_frc
real, dimension(ims:ime , jms:jme) :: tke_pbl
real, dimension(ims:ime , jms:jme) :: wlpool
real :: dtlt
real :: time
real, dimension(ims:ime , jms:jme) :: conprr
real, dimension(ims:ime , jms:jme) :: xmb_deep
real, dimension(ims:ime , jms:jme) :: apr_gr
real, dimension(ims:ime , jms:jme) :: apr_w
real, dimension(ims:ime , jms:jme) :: apr_mc
real, dimension(ims:ime , jms:jme) :: apr_st
real, dimension(ims:ime , jms:jme) :: apr_as
real, dimension(ims:ime , jms:jme) :: xmb_shallow
real, dimension(ims:ime , jms:jme) :: err_deep
real, dimension(ims:ime , jms:jme) :: mass_flux_dp
real, dimension(ims:ime , jms:jme) :: mass_flux_sh
real, dimension(ims:ime , jms:jme) :: mass_flux_md
real, dimension(ims:ime , jms:jme) :: weight_gr
real, dimension(ims:ime , jms:jme) :: weight_w
real, dimension(ims:ime , jms:jme) :: weight_mc
real, dimension(ims:ime , jms:jme) :: weight_st
real, dimension(ims:ime , jms:jme) :: weight_as
real, dimension(ims:ime , jms:jme) :: aa0
real, dimension(ims:ime , jms:jme) :: aa1
real, dimension(ims:ime , jms:jme) :: aa2
real, dimension(ims:ime , jms:jme) :: aa3
real, dimension(ims:ime , jms:jme) :: aa1_bl
real, dimension(ims:ime , jms:jme) :: aa1_cin
real, dimension(ims:ime , jms:jme) :: tau_bl
real, dimension(ims:ime , jms:jme) :: tau_ec
real, dimension(ims:ime , jms:jme) :: xmbdn
real, dimension(ims:ime , jms:jme) :: lightn_dens
real, dimension(ims:ime , jms:jme) :: var2d
real, dimension(ims:ime , jms:jme) :: zkbcon
real, dimension(ims:ime , jms:jme) :: stochastic_sig
real, dimension(ims:ime , jms:jme) :: rh_dicy_fct
real, dimension(ims:ime , jms:jme) :: aa1_adv
real, dimension(ims:ime , jms:jme) :: aa1_radpbl
real, dimension(ims:ime, kms:kme , jms:jme, n_aer) :: sc_aer
real, dimension(ims:ime, kms:kme , jms:jme, n_aer) :: sc_chem
real, dimension(n_aer, kms:kme , ims:ime , jms:jme) :: src_aer
real, dimension(n_aer, kms:kme , ims:ime , jms:jme) :: src_chem
real, dimension(kms:kme , ims:ime , jms:jme) :: thsrc
real, dimension(kms:kme , ims:ime , jms:jme) :: rtsrc
real, dimension(kms:kme , ims:ime , jms:jme) :: clsrc
real, dimension(kms:kme , ims:ime , jms:jme) :: nisrc
real, dimension(kms:kme , ims:ime , jms:jme) :: nlsrc
real, dimension(kms:kme , ims:ime , jms:jme) :: usrc
real, dimension(kms:kme , ims:ime , jms:jme) :: vsrc
real, dimension(kms:kme , ims:ime , jms:jme) :: mup
real, dimension(kms:kme , ims:ime , jms:jme) :: lsfth
real, dimension(kms:kme , ims:ime , jms:jme) :: advf_t
real, dimension(kms:kme , ims:ime , jms:jme) :: lsfrt
real, dimension(kms:kme , ims:ime , jms:jme) :: lsfth_sh
real, dimension(kms:kme , ims:ime , jms:jme) :: lsfrt_sh
real, dimension(kms:kme , ims:ime , jms:jme) :: src_buoy
real, dimension(kms:kme , ims:ime , jms:jme) :: revsu_gf
real, dimension(kms:kme , ims:ime , jms:jme) :: pfil_gf
real, dimension(kms:kme , ims:ime , jms:jme) :: var3d_agf
real, dimension(kms:kme , ims:ime , jms:jme) :: var3d_bgf
real, dimension(kms:kme , ims:ime , jms:jme) :: var3d_cgf
real, dimension(kms:kme , ims:ime , jms:jme) :: var3d_dgf
integer :: itime1
real, dimension(p_nmp,kms:kme , ims:ime , jms:jme) :: sub_qils
real, dimension(p_nmp,kms:kme , ims:ime , jms:jme) :: sub_qlls
real, dimension(p_nmp,kms:kme , ims:ime , jms:jme) :: sub_cfls
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: ierr4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: jmin4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: kdet4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: k224d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: kbcon4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: ktop4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: kpbl4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: klcl4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: kstabi4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: kstabm4d
integer, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: do_this_column
real, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: cprr4d
real, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: xmb4d
real, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: edt4d
real, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: sigma4d
real, dimension(mgmxp,mgmyp,maxiens,ngrids_cp) :: pwav4d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: pcup5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: up_massentr5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: up_massdetr5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: dd_massentr5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: dd_massdetr5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: zup5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: zdn5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: prup5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: prdn5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: clwup5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: tup5d
real, dimension(mgmzp,mgmxp,mgmyp,maxiens,ngrids_cp) :: conv_cld_fr5d
real, dimension(ims:ime , jms:jme) :: grid_length
integer, dimension(ims:ime , jms:jme) :: kpbl
logical :: land
integer :: jk
integer :: nruns
integer :: version
integer :: klon_local
integer :: klev_local
integer :: kte
integer :: nrec
integer :: nvx
integer :: nvar
integer :: nvartotal
integer :: klevgrads(0:300)
integer :: int_byte_size
integer :: n1
integer :: n2
integer :: n3
real :: real_byte_size
integer :: init_stat
Call graph
testmodconvpargf calls initmodconvpargf, gfconparinit, modconvpargfdriver
modconvpargfdriver calls float, cupgf
cupgf calls float, getinversionlayers, getjmin, coldpoolstart, cupupcape, cupupmoisturelight, cupcloudlimits, getzuzdpdf, getpartitionliqice, cupenvclev, cupenv, getlcl, cupupvvel, cupforcingens3dmid, sound, cupenvclevchem, getbuoyancy, cupupmoisture, wrtbinctl, cupforcingens3d, getlateralmassflux, precipcwvfactor, getdelmix, getincloudscchemup, cupupaa1bl, cupddmoisture, cupforcingens3dshal, fct1d3, clouddissipation, getqadv, cupddedt, getincloudscchemdd, rainevapbelowcloudbase, getprecipfluxes, cupoutputens3d, tridiag, getmeltingprofile, genrandom, getwetbulb, ketoheating, getliqicenumberconc, cupupaa0, cupuplightning, cupminimi, getlateralmassfluxdown, rhcontrols, setgradsvar, getcloudbc
cupupmoisturelight calls getcloudbc, fractliqf
cupcloudlimits calls getcloudbc
getzuzdpdf calls float, gammabrams
getpartitionliqice calls fractliqf
cupenvclev calls getinterp
cupenv calls satvap, saturspechum, alog
getlcl calls td
cupupmoisture calls getdelmix, getcloudbc, fractliqf
cupforcingens3d calls float
getincloudscchemup calls getcloudbc, henry
fct1d3 calls 4, 3
cupoutputens3d calls float
genrandom calls ran1
getliqicenumberconc calls makeicenumber, makedropletnumber, fractliqf
cupuplightning calls fractliqf
rhcontrols calls float
getcloudbc calls float
makedropletnumber calls sngl
gammabrams calls intfuncgamma