cupUpMoisture – GF_standalone
cupUpMoisture Subroutine
CC-GPL3
203 statements
Source File
private subroutine cupUpMoisture(name, start_level, klcl, ierr, ierrc, z_cup, qc, qrc, pw, pwav, hc, tempc, xland, po, p_cup, kbcon, ktop, cd, dby, clw_all, t_cup, q_env, gamma_cup, zu, qes_cup, k22, qe_cup, zqexec, use_excess, ccn, rho, up_massentr, up_massdetr, psum, psumh, c1d, x_add_buoy, vvel2d, vvel1d, zws, entr_rate_2d, itest, itf, ktf, ipr, jpr, its, ite, kts, kte)
brief
Note
Project: MONAN Author(s): Saulo Freitas [SRF] e Georg Grell [GAG] e-mail: saulo.r.de.freitas@gmail.com, georg.a.grell@noaa.gov Date: 2014
Full description: brief
Warning
Under the terms of the GNU General Public version 3
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name
integer, intent(in) :: start_level(its:ite)
integer, intent(in) :: klcl(its:ite)
integer, intent(inout) :: ierr(its:ite)
ierr error value, maybe modified in this routine
character(len=128), intent(inout) :: ierrc(its:ite)
real, intent(in) :: z_cup(its:ite,kts:kte)
real, intent(out) :: qc(its:ite,kts:kte)
cloud q (including liquid water) after entrainment
real, intent(out) :: qrc(its:ite,kts:kte)
liquid water content in cloud after rainout
real, intent(out) :: pw(its:ite,kts:kte)
condensate that will fall out at that level
real, intent(out) :: pwav(its:ite)
totan normalized integrated condensate (I1)
real, intent(in) :: hc(its:ite,kts:kte)
real, intent(out) :: tempc(its:ite,kts:kte)
real, intent(in) :: xland(its:ite)
real, intent(in) :: po(its:ite,kts:kte)
real, intent(in) :: p_cup(its:ite,kts:kte)
integer, intent(in) :: kbcon(its:ite)
integer, intent(in) :: ktop(its:ite)
real, intent(in) :: cd(its:ite,kts:kte)
detrainment function
real, intent(in) :: dby(its:ite,kts:kte)
buoancy term
real, intent(out) :: clw_all(its:ite,kts:kte)
real, intent(in) :: t_cup(its:ite,kts:kte)
real, intent(in) :: q_env(its:ite,kts:kte)
environmental q on model levels
real, intent(in) :: gamma_cup(its:ite,kts:kte)
gamma on model cloud levels
real, intent(in) :: zu(its:ite,kts:kte)
normalized updraft mass flux
real, intent(in) :: qes_cup(its:ite,kts:kte)
saturation q on model cloud levels
integer, intent(in) :: k22(its:ite)
real, intent(in) :: qe_cup(its:ite,kts:kte)
environmental q on model cloud levels
real, intent(in) :: zqexec(its:ite)
integer, intent(in) :: use_excess
real, intent(in) :: ccn(its:ite)
real, intent(in) :: rho(its:ite,kts:kte)
real, intent(in) :: up_massentr(its:ite,kts:kte)
real, intent(in) :: up_massdetr(its:ite,kts:kte)
real, intent(out) :: psum(its:ite)
real, intent(out) :: psumh(its:ite)
real, intent(in) :: c1d(its:ite,kts:kte)
real, intent(in) :: x_add_buoy(its:ite)
real, intent(in) :: vvel2d(its:ite,kts:kte)
real, intent(in) :: vvel1d(its:ite)
real, intent(in) :: zws(its:ite)
real, intent(in) :: entr_rate_2d(its:ite,kts:kte)
integer, intent(in) :: itest
integer, intent(in) :: itf
integer, intent(in) :: ktf
integer, intent(in) :: ipr
integer, intent(in) :: jpr
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: kts
integer, intent(in) :: kte
Calls
Called by
Contents
Call graph
cupupmoisture calls getcloudbc, getdelmix, fractliqf
getcloudbc calls float
cupgf calls cupupmoisture
modconvpargfdriver calls cupgf
testmodconvpargf calls modconvpargfdriver