cupGf – GF_standalone
cupGf Subroutine
CC-GPL3
1723 statements
Source File
private subroutine cupGf(its, ite, kts, kte, itf, ktf, mtp, nmp, fscav, cumulus, ichoice, entr_rate_input, use_excess, dx, stochastic_sig, col_sat, tke_pbl, rh_dicycle_fct, wlpool, dtime, kpbl, ztexec, zqexec, ccn, rho, omeg, t, q, z1, h_sfc_flux, le_sfc_flux, xlons, xlats, xland, tn, qo, tn_bl, qo_bl, tn_adv, qo_adv, zo, po, tsur, psur, us, vs, dm2d, se_chem, zws, dhdt, buoy_exc, mpqi, mpql, mpcf, last_ierr, outt, outq, outqc, outu, outv, outnliq, outnice, outbuoy, outmpqi, outmpql, outmpcf, out_chem, ierr, jmin, klcl, k22, kbcon, ktop, kstabi, kstabm, pre, xmb, edto, pwavo, sig, po_cup, up_massentro, up_massdetro, dd_massentro, dd_massdetro, zuo, zdo, pwo, pwdo, qrco, tup, clfrac, aaa0_, aa1_, aa1_adv_, aa1_radpbl_, aa2_, aa3_, aa1_bl_, aa1_cin_, tau_bl_, tau_ec_, lightn_dens, var2d, revsu_gf, prfil_gf, var3d_agf, var3d_bgf, tpert)
brief
Note
Project: MONAN Author(s): Saulo Freitas [SRF] e Georg Grell [GAG] e-mail: saulo.r.de.freitas@gmail.com, georg.a.grell@noaa.gov Date: 2014
Full description: brief
Warning
Under the terms of the GNU General Public version 3
tn_x = tn qo_x = qo go to 333
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: kts
integer, intent(in) :: kte
integer, intent(in) :: itf
integer, intent(in) :: ktf
integer, intent(in) :: mtp
integer, intent(in) :: nmp
real, intent(in) :: fscav(mtp)
character(len=*), intent(in) :: cumulus
integer, intent(in) :: ichoice
real, intent(in) :: entr_rate_input
integer, intent(in) :: use_excess
real, intent(inout) :: dx(its:ite)
real, intent(in) :: stochastic_sig(its:ite)
real, intent(in) :: col_sat(its:ite)
real, intent(in) :: tke_pbl(its:ite)
real, intent(inout) :: rh_dicycle_fct(its:ite)
real, intent(inout) :: wlpool(its:ite)
real, intent(in) :: dtime
integer, intent(inout) :: kpbl(its:ite)
real, intent(inout) :: ztexec(its:ite)
real, intent(inout) :: zqexec(its:ite)
real, intent(inout) :: ccn(its:ite)
real, intent(inout) :: rho(its:ite,kts:kte)
real, intent(inout) :: omeg(its:ite,kts:kte,1:p_ens4)
real, intent(inout) :: t(its:ite,kts:kte)
environmental temp
real, intent(inout) :: q(its:ite,kts:kte)
environmental mixing ratio
real, intent(inout) :: z1(its:ite)
real, intent(inout) :: h_sfc_flux(its:ite)
real, intent(inout) :: le_sfc_flux(its:ite)
real, intent(inout) :: xlons(its:ite)
real, intent(inout) :: xlats(its:ite)
real, intent(inout) :: xland(its:ite)
real, intent(inout) :: tn(its:ite,kts:kte)
real, intent(inout) :: qo(its:ite,kts:kte)
real, intent(inout) :: tn_bl(its:ite,kts:kte)
real, intent(inout) :: qo_bl(its:ite,kts:kte)
real, intent(inout) :: tn_adv(its:ite,kts:kte)
real, intent(inout) :: qo_adv(its:ite,kts:kte)
real, dimension(its:ite, kts:kte) :: zo
real, intent(inout) :: po(its:ite,kts:kte)
real, intent(inout) :: tsur(its:ite)
real, intent(inout) :: psur(its:ite)
real, intent(inout) :: us(its:ite,kts:kte)
real, intent(inout) :: vs(its:ite,kts:kte)
real, intent(inout) :: dm2d(its:ite,kts:kte)
real, intent(inout) :: se_chem(mtp,its:ite,kts:kte)
real, intent(inout) :: zws(its:ite)
real, intent(inout) :: dhdt(its:ite,kts:kte)
real, intent(inout) :: buoy_exc(its:ite,kts:kte)
real, intent(inout) :: mpqi(nmp,its:ite,kts:kte)
real, intent(inout) :: mpql(nmp,its:ite,kts:kte)
real, intent(inout) :: mpcf(nmp,its:ite,kts:kte)
integer, intent(inout) :: last_ierr(its:ite)
real, intent(inout) :: outt(its:ite,kts:kte)
output temp tendency (per s)
real, intent(inout) :: outq(its:ite,kts:kte)
output q tendency (per s)
real, intent(inout) :: outqc(its:ite,kts:kte)
output qc tendency (per s)
real, intent(inout) :: outu(its:ite,kts:kte)
real, intent(inout) :: outv(its:ite,kts:kte)
real, intent(inout) :: outnliq(its:ite,kts:kte)
real, intent(inout) :: outnice(its:ite,kts:kte)
real, intent(inout) :: outbuoy(its:ite,kts:kte)
real, intent(inout) :: outmpqi(nmp,its:ite,kts:kte)
real, intent(inout) :: outmpql(nmp,its:ite,kts:kte)
real, intent(inout) :: outmpcf(nmp,its:ite,kts:kte)
real, intent(inout) :: out_chem(mtp,its:ite,kts:kte)
integer, intent(inout) :: ierr(its:ite)
integer, intent(inout) :: jmin(its:ite)
integer, intent(inout) :: klcl(its:ite)
integer, intent(inout) :: k22(its:ite)
integer, intent(inout) :: kbcon(its:ite)
integer, intent(inout) :: ktop(its:ite)
integer, intent(inout) :: kstabi(its:ite)
integer, intent(inout) :: kstabm(its:ite)
real, intent(out) :: pre(its:ite)
real, intent(inout) :: xmb(its:ite)
real, intent(inout) :: edto(its:ite)
real, intent(inout) :: pwavo(its:ite)
real, intent(out) :: sig(its:ite)
real, intent(inout) :: po_cup(its:ite,kts:kte)
real, intent(inout) :: up_massentro(its:ite,kts:kte)
real, intent(inout) :: up_massdetro(its:ite,kts:kte)
real, intent(inout) :: dd_massentro(its:ite,kts:kte)
real, intent(inout) :: dd_massdetro(its:ite,kts:kte)
real, intent(inout) :: zuo(its:ite,kts:kte)
real, intent(inout) :: zdo(its:ite,kts:kte)
real, intent(inout) :: pwo(its:ite,kts:kte)
real, intent(inout) :: pwdo(its:ite,kts:kte)
real, intent(inout) :: qrco(its:ite,kts:kte)
real, intent(inout) :: tup(its:ite,kts:kte)
real, intent(inout) :: clfrac(its:ite,kts:kte)
real, intent(inout) :: aaa0_(its:ite)
real, intent(inout) :: aa1_(its:ite)
real, intent(inout) :: aa1_adv_(its:ite)
real, intent(inout) :: aa1_radpbl_(its:ite)
real, intent(inout) :: aa2_(its:ite)
real, intent(inout) :: aa3_(its:ite)
real, intent(inout) :: aa1_bl_(its:ite)
real, intent(inout) :: aa1_cin_(its:ite)
real, intent(inout) :: tau_bl_(its:ite)
real, intent(inout) :: tau_ec_(its:ite)
real, intent(out) :: lightn_dens(its:ite)
real, intent(out) :: var2d(its:ite)
real, intent(inout) :: revsu_gf(its:ite,kts:kte)
real, intent(inout) :: prfil_gf(its:ite,kts:kte)
real, intent(inout) :: var3d_agf(its:ite,kts:kte)
real, intent(inout) :: var3d_bgf(its:ite,kts:kte)
real, intent(inout) :: tpert(its:ite,kts:kte)
Calls
Called by
Contents
Call graph
cupgf calls getinversionlayers, getjmin, coldpoolstart, cupupcape, cupupmoisturelight, cupcloudlimits, getzuzdpdf, getpartitionliqice, cupenvclev, cupenv, getlcl, cupupvvel, cupforcingens3dmid, sound, getmeltingprofile, cupenvclevchem, getbuoyancy, cupupmoisture, wrtbinctl, cupforcingens3d, getlateralmassflux, precipcwvfactor, getdelmix, getincloudscchemup, cupupaa1bl, cupddmoisture, cupforcingens3dshal, float, fct1d3, getqadv, cupddedt, getincloudscchemdd, rainevapbelowcloudbase, getprecipfluxes, cupoutputens3d, clouddissipation, tridiag, genrandom, getwetbulb, ketoheating, getliqicenumberconc, cupupaa0, cupuplightning, cupminimi, getlateralmassfluxdown, rhcontrols, setgradsvar, getcloudbc
cupupmoisturelight calls getcloudbc, fractliqf
cupcloudlimits calls getcloudbc
getzuzdpdf calls float, gammabrams
getpartitionliqice calls fractliqf
cupenvclev calls getinterp
cupenv calls satvap, saturspechum, alog
getlcl calls td
cupupmoisture calls getdelmix, getcloudbc, fractliqf
cupforcingens3d calls float
getincloudscchemup calls getcloudbc, henry
fct1d3 calls 4, 3
cupoutputens3d calls float
genrandom calls ran1
getliqicenumberconc calls makeicenumber, makedropletnumber, fractliqf
cupuplightning calls fractliqf
rhcontrols calls float
getcloudbc calls float
makedropletnumber calls sngl
gammabrams calls intfuncgamma
modconvpargfdriver calls cupgf
testmodconvpargf calls modconvpargfdriver