cupOutputEns3d – GF_standalone
cupOutputEns3d Subroutine
CC-GPL3
201 statements
Source File
private subroutine cupOutputEns3d(cumulus, xff_shal, xff_mid, xf_ens, ierr, dellat, dellaq, dellaqc, outtem, outq, outqc, zu, pre, pw, xmb, ktop, nx, nx2, ierr2, ierr3, pr_ens, maxens3, ensdim, sig, xland1, ichoice, ipr, jpr, itf, ktf, its, ite, kts, kte, xf_dicycle, outu, outv, dellu, dellv, dtime, po_cup, kbcon, dellabuoy, outbuoy, dellampqi, outmpqi, dellampql, outmpql, dellampcf, outmpcf, nmp, rh_dicycle_fct, xf_coldpool, wlpool_bcon)
brief
Note
Project: MONAN Author(s): Saulo Freitas [SRF] e Georg Grell [GAG] e-mail: saulo.r.de.freitas@gmail.com, georg.a.grell@noaa.gov Date: 2014
Full description: brief
Warning
 Under the terms of the GNU General Public version 3
! if(ierr(i) /= 0) cycle
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: cumulus
real, intent(in) :: xff_shal(its:ite,p_shall_closures)
real, intent(in) :: xff_mid(its:ite,maxens3)
real, intent(inout) :: xf_ens(its:ite,1:ensdim)
ensemble mass fluxes
integer, intent(inout) :: ierr(its:ite)
ierr error value, maybe modified in this routine
real, intent(inout) :: dellat(its:ite,kts:kte)
change of temperature per unit mass flux of cloud ensemble
real, intent(inout) :: dellaq(its:ite,kts:kte)
change of q per unit mass flux of cloud ensemble
real, intent(inout) :: dellaqc(its:ite,kts:kte)
change of qc per unit mass flux of cloud ensemble
real, intent(out) :: outtem(its:ite,kts:kte)
output temp tendency (per s)
real, intent(out) :: outq(its:ite,kts:kte)
output q tendency (per s)
real, intent(out) :: outqc(its:ite,kts:kte)
output qc tendency (per s)
real, intent(in) :: zu(its:ite,kts:kte)
real, intent(out) :: pre(its:ite)
output precip
real, intent(inout) :: pw(its:ite,kts:kte)
epsilon*pd (ensemble dependent)
real, intent(out) :: xmb(its:ite)
total base mass flux
integer, intent(in) :: ktop(its:ite)
integer, intent(in) :: nx
integer, intent(in) :: nx2
integer, intent(inout) :: ierr2(its:ite)
integer, intent(inout) :: ierr3(its:ite)
real, intent(inout) :: pr_ens(its:ite,1:ensdim)
precipitation ensembles
integer, intent(in) :: maxens3
integer, intent(in) :: ensdim
real, intent(in) :: sig(its:ite)
real, intent(inout) :: xland1(its:ite)
integer, intent(in) :: ichoice
integer, intent(in) :: ipr
integer, intent(in) :: jpr
integer, intent(in) :: itf
integer, intent(in) :: ktf
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: kts
integer, intent(in) :: kte
real, intent(inout) :: xf_dicycle(its:ite)
real, intent(out) :: outu(its:ite,kts:kte)
real, intent(out) :: outv(its:ite,kts:kte)
real, intent(inout) :: dellu(its:ite,kts:kte)
real, intent(inout) :: dellv(its:ite,kts:kte)
real, intent(in) :: dtime
real, intent(in) :: po_cup(its:ite,kts:kte)
integer, intent(in) :: kbcon(its:ite)
real, intent(inout) :: dellabuoy(its:ite,kts:kte)
real, intent(out) :: outbuoy(its:ite,kts:kte)
real, intent(in) :: dellampqi(nmp,its:ite,kts:kte)
real, intent(out) :: outmpqi(nmp,its:ite,kts:kte)
real, intent(in) :: dellampql(nmp,its:ite,kts:kte)
real, intent(out) :: outmpql(nmp,its:ite,kts:kte)
real, intent(in) :: dellampcf(nmp,its:ite,kts:kte)
real, intent(out) :: outmpcf(nmp,its:ite,kts:kte)
integer, intent(in) :: nmp
real, intent(in) :: rh_dicycle_fct(its:ite)
real, intent(inout) :: xf_coldpool(its:ite)
real, intent(in) :: wlpool_bcon(its:ite)
Calls
Called by
Contents
Call graph
cupoutputens3d calls float
cupgf calls cupoutputens3d
modconvpargfdriver calls cupgf
testmodconvpargf calls modconvpargfdriver