getInCloudScChemDd – GF_standalone
getInCloudScChemDd Subroutine
CC-GPL3
71 statements
Source File
private subroutine getInCloudScChemDd(cumulus, fscav, mtp, se, se_cup, sc_dn, pw_dn, pw_up, sc_up, tot_pw_up_chem, tot_pw_dn_chem, z_cup, rho, po_cup, qrcdo, pwdo, pwevo, edto, zdo, dd_massentro, dd_massdetro, pwavo, pwo, jmin, ierr, itf, ktf, its, ite, kts, kte)
brief
Note
Project: MONAN Author(s): Saulo Freitas [SRF] e Georg Grell [GAG] e-mail: saulo.r.de.freitas@gmail.com, georg.a.grell@noaa.gov Date: 2014
Full description: brief
Warning
Under the terms of the GNU General Public version 3
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: cumulus
real, intent(in) :: fscav(mtp)
integer, intent(in) :: mtp
real, intent(in) :: se(mtp,its:ite,kts:kte)
real, intent(in) :: se_cup(mtp,its:ite,kts:kte)
real, intent(out) :: sc_dn(mtp,its:ite,kts:kte)
real, intent(out) :: pw_dn(mtp,its:ite,kts:kte)
real, intent(in) :: pw_up(mtp,its:ite,kts:kte)
real, intent(in) :: sc_up(mtp,its:ite,kts:kte)
real, intent(in) :: tot_pw_up_chem(mtp,its:ite)
real, intent(out) :: tot_pw_dn_chem(mtp,its:ite)
real, intent(in) :: z_cup(its:ite,kts:kte)
real, intent(in) :: rho(its:ite,kts:kte)
real, intent(in) :: po_cup(its:ite,kts:kte)
real, intent(in) :: qrcdo(its:ite,kts:kte)
real, intent(in) :: pwdo(its:ite,kts:kte)
real, intent(in) :: pwevo(its:ite)
real, intent(in) :: edto(its:ite)
real, intent(in) :: zdo(its:ite,kts:kte)
real, intent(in) :: dd_massentro(its:ite,kts:kte)
real, intent(in) :: dd_massdetro(its:ite,kts:kte)
real, intent(in) :: pwavo(its:ite)
real, intent(in) :: pwo(its:ite,kts:kte)
integer, intent(in) :: jmin(its:ite)
integer, intent(in) :: ierr(its:ite)
integer, intent(in) :: itf
integer, intent(in) :: ktf
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: kts
integer, intent(in) :: kte
Called by
Contents
Call graph
cupgf calls getincloudscchemdd
modconvpargfdriver calls cupgf
testmodconvpargf calls modconvpargfdriver