getLiqIceNumberConc – GF_standalone
getLiqIceNumberConc Subroutine
CC-GPL3
32 statements
Source File
private subroutine getLiqIceNumberConc(itf, ktf, its, ite, kts, kte, ierr, ktop, dtime, rho, outqc, tempco, outnliq, outnice)
brief
Note
Project: MONAN Author(s): Saulo Freitas [SRF] e Georg Grell [GAG] e-mail: saulo.r.de.freitas@gmail.com, georg.a.grell@noaa.gov Date: 2014
Full description: brief
Warning
Under the terms of the GNU General Public version 3
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: itf
integer, intent(in) :: ktf
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: kts
integer, intent(in) :: kte
integer, intent(in) :: ierr(its:ite)
integer, intent(in) :: ktop(its:ite)
real, intent(in) :: dtime
real, intent(in) :: rho(its:ite,kts:kte)
real, intent(in) :: outqc(its:ite,kts:kte)
real, intent(in) :: tempco(its:ite,kts:kte)
real, intent(out) :: outnliq(its:ite,kts:kte)
real, intent(out) :: outnice(its:ite,kts:kte)
Calls
Called by
Contents
Call graph
getliqicenumberconc calls fractliqf, makeicenumber, makedropletnumber
makedropletnumber calls sngl
cupgf calls getliqicenumberconc
modconvpargfdriver calls cupgf
testmodconvpargf calls modconvpargfdriver