IntFuncGamma – GF_standalone
IntFuncGamma Function
CC-GPL3
8 statements
Source File
private pure function IntFuncGamma(x, y) result(z)
brief
Note
Project : MONAN Author(s): Demerval Moreira [DSM] e-mail: demerval.moreira@unesp.br Date: 2014
Full description: brief
Warning
Under the terms of the GNU General Public version 3
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: x
real, intent(in) :: y
Return Value real
Called by
Contents
Call graph
gammabrams calls intfuncgamma
getzuzdpdf calls gammabrams
cupgf calls getzuzdpdf
modconvpargfdriver calls cupgf
testmodconvpargf calls modconvpargfdriver