modConvParGFDriver – GF_standalone
modConvParGFDriver Subroutine
CC-GPL3
571 statements
Source File
public subroutine modConvParGFDriver(mxp, myp, mzp, mtp, nmp, time, itime1, ims, ime, jms, jme, kms, kme, its, ite, jts, jte, kts, kte, flip, fscav, mynum, dt, dx2d, stochastic_sig, zm, zt, dm, lons, lats, aot500, temp2m, sflux_r, sflux_t, qexcp, hexcp, wlpool, topt, xland, sfc_press, kpbl, tke_pbl, col_sat, u_wind, v_wind, w_wind, temp, press, rvap, mp_ice, mp_liq, mp_cf, curr_rvap, tracer, buoy_exc, rthften, rqvften, rth_advten, rthblten, rqvblten, conprr, lightn_dens, rh_dicycle_fct, rthcuten, rqvcuten, rqccuten, rnlcuten, rnicuten, rucuten, rvcuten, sub_mpqi, sub_mpql, sub_mpcf, rbuoycuten, rchemcuten, revsu_gf, prfil_gf, do_this_column, ierr4d, jmin4d, klcl4d, k224d, kbcon4d, ktop4d, kstabi4d, kstabm4d, cprr4d, xmb4d, edt4d, pwav4d, sigma4d, pcup5d, up_massentr5d, up_massdetr5d, dd_massentr5d, dd_massdetr5d, zup5d, zdn5d, prup5d, prdn5d, clwup5d, tup5d, conv_cld_fr5d, aa0, aa1, aa1_adv, a1_radpbl, aa1_bl, aa2, aa3, aa1_cin, tau_bl, tau_ec, var2d, var3d_agf, var3d_bgf, var3d_cgf, var3d_dgf)
Driver
Note
Project: MONAN Author(s): Saulo Freitas [SRF] e Georg Grell [GAG] e-mail: saulo.r.de.freitas@gmail.com, georg.a.grell@noaa.gov Date: 2014
Full description: Driver
Warning
Under the terms of the GNU General Public version 3
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: mxp
integer, intent(in) :: myp
integer, intent(in) :: mzp
integer, intent(in) :: mtp
integer, intent(in) :: nmp
real, intent(in) :: time
integer, intent(in) :: itime1
integer, intent(in) :: ims
integer, intent(in) :: ime
integer, intent(in) :: jms
integer, intent(in) :: jme
integer, intent(in) :: kms
integer, intent(in) :: kme
integer, intent(in) :: its
integer, intent(in) :: ite
integer, intent(in) :: jts
integer, intent(in) :: jte
integer, intent(in) :: kts
integer, intent(in) :: kte
integer, intent(in) :: flip(mzp)
real, intent(inout) :: fscav(mtp)
integer, intent(in) :: mynum
real, intent(in) :: dt
real, intent(inout) :: dx2d(its:ite,jts:jte)
real, intent(in) :: stochastic_sig(its:ite,jts:jte)
real, intent(in) :: zm(kts:kte,its:ite,jts:jte)
real, intent(in) :: zt(kts:kte,its:ite,jts:jte)
real, intent(in) :: dm(kts:kte,its:ite,jts:jte)
real, intent(in) :: lons(its:ite,jts:jte)
real, intent(in) :: lats(its:ite,jts:jte)
real, intent(in) :: aot500(its:ite,jts:jte)
real, intent(in) :: temp2m(its:ite,jts:jte)
real, intent(in) :: sflux_r(its:ite,jts:jte)
real, intent(in) :: sflux_t(its:ite,jts:jte)
real, intent(in) :: qexcp(kts:kte,its:ite,jts:jte)
real, intent(in) :: hexcp(kts:kte,its:ite,jts:jte)
real, intent(inout) :: wlpool(its:ite,jts:jte)
real, intent(in) :: topt(its:ite,jts:jte)
real, intent(in) :: xland(its:ite,jts:jte)
real, intent(in) :: sfc_press(its:ite,jts:jte)
integer, intent(in) :: kpbl(its:ite,jts:jte)
real, intent(in) :: tke_pbl(its:ite,jts:jte)
real, intent(in) :: col_sat(its:ite,jts:jte)
real, intent(in) :: u_wind(kts:kte,its:ite,jts:jte)
real, intent(in) :: v_wind(kts:kte,its:ite,jts:jte)
real, intent(in) :: w_wind(kts:kte,its:ite,jts:jte)
real, intent(in) :: temp(kts:kte,its:ite,jts:jte)
real, intent(in) :: press(kts:kte,its:ite,jts:jte)
real, intent(in) :: rvap(kts:kte,its:ite,jts:jte)
real, intent(in) :: mp_ice(nmp,kts:kte,its:ite,jts:jte)
real, intent(in) :: mp_liq(nmp,kts:kte,its:ite,jts:jte)
real, intent(in) :: mp_cf(nmp,kts:kte,its:ite,jts:jte)
real, intent(in) :: curr_rvap(kts:kte,its:ite,jts:jte)
real, intent(in) :: tracer(its:ite,jts:jte,kts:kte,mtp)
tracer has different data structure (i,j,k,ispc) ***
real, intent(in) :: buoy_exc(kts:kte,its:ite,jts:jte)
real, intent(in) :: rthften(kts:kte,its:ite,jts:jte)
real, intent(in) :: rqvften(kts:kte,its:ite,jts:jte)
real, intent(in) :: rth_advten(kts:kte,its:ite,jts:jte)
real, intent(in) :: rthblten(kts:kte,its:ite,jts:jte)
real, intent(in) :: rqvblten(kts:kte,its:ite,jts:jte)
real, intent(out) :: conprr(its:ite,jts:jte)
real, intent(out) :: lightn_dens(its:ite,jts:jte)
real, intent(inout) :: rh_dicycle_fct(its:ite,jts:jte)
real, intent(out) :: rthcuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: rqvcuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: rqccuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: rnlcuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: rnicuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: rucuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: rvcuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: sub_mpqi(nmp,kts:kte,its:ite,jts:jte)
real, intent(out) :: sub_mpql(nmp,kts:kte,its:ite,jts:jte)
real, intent(out) :: sub_mpcf(nmp,kts:kte,its:ite,jts:jte)
real, intent(out) :: rbuoycuten(kts:kte,its:ite,jts:jte)
real, intent(out) :: rchemcuten(mtp,kts:kte,its:ite,jts:jte)
rchemcuten uses the GF data structure (ispc,k,i,j) ***
real, intent(out) :: revsu_gf(kts:kte,its:ite,jts:jte)
real, intent(out) :: prfil_gf(kts:kte,its:ite,jts:jte)
integer, intent(inout) :: do_this_column(its:ite,jts:jte)
integer, intent(inout) :: ierr4d(mxp,myp,p_maxiens)
integer, intent(inout) :: jmin4d(mxp,myp,p_maxiens)
integer, intent(inout) :: klcl4d(mxp,myp,p_maxiens)
integer, intent(inout) :: k224d(mxp,myp,p_maxiens)
integer, intent(inout) :: kbcon4d(mxp,myp,p_maxiens)
integer, intent(inout) :: ktop4d(mxp,myp,p_maxiens)
integer, intent(inout) :: kstabi4d(mxp,myp,p_maxiens)
integer, intent(inout) :: kstabm4d(mxp,myp,p_maxiens)
real, intent(inout) :: cprr4d(mxp,myp,p_maxiens)
real, intent(inout) :: xmb4d(mxp,myp,p_maxiens)
real, intent(inout) :: edt4d(mxp,myp,p_maxiens)
real, intent(inout) :: pwav4d(mxp,myp,p_maxiens)
real, intent(inout) :: sigma4d(mxp,myp,p_maxiens)
real, intent(inout) :: pcup5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: up_massentr5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: up_massdetr5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: dd_massentr5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: dd_massdetr5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: zup5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: zdn5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: prup5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: prdn5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: clwup5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: tup5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: conv_cld_fr5d(mxp,myp,mzp,p_maxiens)
real, intent(inout) :: aa0(mxp,myp)
real, intent(inout) :: aa1(mxp,myp)
real, intent(inout) :: aa1_adv(mxp,myp)
real, intent(inout) :: a1_radpbl(mxp,myp)
real, intent(inout) :: aa1_bl(mxp,myp)
real, intent(inout) :: aa2(mxp,myp)
real, intent(inout) :: aa3(mxp,myp)
real, intent(inout) :: aa1_cin(mxp,myp)
real, intent(inout) :: tau_bl(mxp,myp)
real, intent(inout) :: tau_ec(mxp,myp)
real, intent(inout) :: var2d(mxp,myp)
real, intent(out) :: var3d_agf(kts:kte,its:ite,jts:jte)
real, intent(out) :: var3d_bgf(kts:kte,its:ite,jts:jte)
real, intent(out) :: var3d_cgf(kts:kte,its:ite,jts:jte)
real, intent(out) :: var3d_dgf(kts:kte,its:ite,jts:jte)
Calls
Called by
Contents
Call graph
modconvpargfdriver calls float, cupgf
cupgf calls float, getinversionlayers, getjmin, coldpoolstart, cupupcape, cupupmoisturelight, cupcloudlimits, getzuzdpdf, getpartitionliqice, cupenvclev, cupenv, getlcl, cupupvvel, cupforcingens3dmid, sound, cupenvclevchem, getbuoyancy, cupupmoisture, wrtbinctl, cupforcingens3d, getlateralmassflux, precipcwvfactor, getdelmix, getincloudscchemup, cupupaa1bl, cupddmoisture, cupforcingens3dshal, fct1d3, clouddissipation, getqadv, cupddedt, getincloudscchemdd, rainevapbelowcloudbase, getprecipfluxes, cupoutputens3d, tridiag, getmeltingprofile, genrandom, getwetbulb, ketoheating, getliqicenumberconc, cupupaa0, cupuplightning, cupminimi, getlateralmassfluxdown, rhcontrols, setgradsvar, getcloudbc
cupupmoisturelight calls getcloudbc, fractliqf
cupcloudlimits calls getcloudbc
getzuzdpdf calls float, gammabrams
getpartitionliqice calls fractliqf
cupenvclev calls getinterp
cupenv calls satvap, saturspechum, alog
getlcl calls td
cupupmoisture calls getdelmix, getcloudbc, fractliqf
cupforcingens3d calls float
getincloudscchemup calls getcloudbc, henry
fct1d3 calls 4, 3
cupoutputens3d calls float
genrandom calls ran1
getliqicenumberconc calls makeicenumber, makedropletnumber, fractliqf
cupuplightning calls fractliqf
rhcontrols calls float
getcloudbc calls float
makedropletnumber calls sngl
gammabrams calls intfuncgamma
testmodconvpargf calls modconvpargfdriver